---
title: "Classificando IDHM"
date: "11/10/2018"
author: "Camila Simões, Leonardo Filgueira"
output:
  rmdformats::readthedown:
    highlight: kate
    
---

# INTRODUÇÃO 

De acordo com o Programa das Nações Unidas para o Desenvolvimento  [(PNUD)](http://www.br.undp.org/content/brazil/pt/home/idh0/conceitos/o-que-e-desenvolvimento-humano.html), o conceito de desenvolvimento humano consiste em avaliar as oportunidades e capacidades individuais da população. Ao pensar em desenvolvimento humano, pode ser intuitivo associá-lo imediatamente ao ponto de vista econômico, porém a ideia é considerar também aspectos sociais, culturais e políticos.

A proposta do Índice de Desenvolvimento Humano tem por objetivo oferecer uma alternativa à análise do progresso social a partir, do ponto de vista econômico, utilizando o Produto Interno Bruto (PIB). Embora, seja uma nova possibilidade de mensurar o desenvolvimento, o índice não contempla a representação da "felicidade", ou seja, não considera a pessoa na sua individualidade, mas seu comportamento em relação a um grupo (sociedade).

Sob a perspectiva municipal, foi adaptado o conceito de Índice de Desenvolvimento Humano para as cidades (IDHM). O indicador apresenta a mesma ideia do IDH de forma geral.

## CONTEXTUALIZAÇÃO DO PROBLEMA 

Os municípios do estado do Rio de Janeiro apresentam comportamentos diferentes. Algumas diversidades podem ser observadas de acordo com a posição geográfica, a condição social, cultural, histórica, econômica, entre outras. Esses atributos podem ser responsáveis por diferentes níveis de desenvolvimento. Portanto, este trabalho consiste em classificar o IDHM a partir de informações municipais.

# DADOS 

```{r, echo=F, warning=F,message=F}

require(readxl)
require(dplyr)
require(rpart)
require(rpart.plot)
require(magrittr)

dados <- read_xlsx("AtlasBrasil_Consulta (1).xlsx")
regiao <- read_xlsx("ordem_mun.xlsx")
```

O banco de dados é formado por `r nrow(dados)` registros, referentes aos `r nrow(dados)`  municípios do estado do Rio de Janeiro. As informações foram extraídas do [Atlas Brasil](http://www.atlasbrasil.org.br/2013/pt/consulta/) . Inicialmente, foram coletadas 
`r ncol(dados) - 2` variáveis. Em seguida, também foram obtidas informações sobre as mesorregiões correspondentes aos municípios.

## METODOLOGIA

Para obtermos e avaliarmos a classificação do IDHM, a base de dados foi dividida em treino e teste. A base a ser treinada conta com 80% dos municípios.  As cidades restantes, que indicam 20% da base de dados, serão utilizadas para teste.

<!-- Inserir chunk de treino e teste -->


Para a classificação do IDHM foi utilizada a técnica de mineração de dados conhecida como **árvore de classificação**. A árvore analisa como cada variável influencia na distribuição do atributo a ser classificado.

Para a execução do algoritmo, utilizamos a função `rpart` do pacote `rpart` e, para a visualização da árvore, foi utilizada a função `rpart.plot` do pacote `rpart.plot`.

<!-- Inserir o algoritmo  -->


# CONCLUSÃO 


